from typing import List
from fastapi import UploadFile, FastAPI, Form, File
from fastapi.middleware.cors import CORSMiddleware
import os
import pandas as pd
import uvicorn

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

LOG_FILE_PATH = "results/exp_standard_v3/experiment_log.csv"

# ------------------------------------------------------------------------
# 하드코딩 답변: Markdown + 줄바꿈 포함
# ------------------------------------------------------------------------
HARDCODED_ANSWERS = {
    "vmware_release_timeline": """\
VMware vCenter Server Release Timeline Below is a structured timeline of the release dates for various versions of VMware vCenter Server:

| Version | Release Date |
|-----------------------------|-------------|
| VMware vCenter Server 7.0 Update 3m | 22 JUN 2023 |
| VMware vCenter Server 7.0 Update 3n | 06 JUL 2023 |
| VMware vCenter Server 7.0 Update 3r | 17 JUN 2024 |

This table provides a clear and concise overview of the release dates for the specified versions of VMware vCenter Server. If additional versions or details are required, please specify.
""",
    "ai_act_healthcare_report": """\
Technical Report: Noteworthy AI Act Regulations for a Virtual AI Assistant in the Healthcare Domain

### 1. Introduction
This report identifies and summarizes the most relevant articles and sections of the AI Act regulations that pertain to the deployment of a virtual AI assistant in the healthcare domain. The report is structured to ensure high readability and easy navigation through the key regulatory requirements.

### 3. Specific Articles and Annexes
The following articles and annexes are noteworthy for a virtual AI assistant in healthcare:

| Articles | Annexes |
|-------------|-------------|
| Article 9  | Annex III |
| Article 11 | Annex IV |
| Article 18 |  |
| Article 19 |  |
| Article 20 |  |
| Article 40 |  |
| Article 43 |  |
| Article 48 |  |
| Article 49 |  |
| Article 61 |  |
| Article 62 |  |
| Article 74 |  |
| Directive 2013/36/EU |  |

### 10. Cooperation and Obligations
| Articles | Obligations |
|-------------|----------------|
| Article 23 | Cooperation with competent authorities |
| Article 24 | Obligations of product manufacturers |
| Article 25 | Authorised representatives |
| Article 26 | Obligations of importers |

This structured format ensures high readability and easy navigation through the regulatory requirements for a virtual AI assistant in the healthcare domain.
""",
    "national_parks_brown_bears": """\
National Parks for Brown Bear Sightings Below is a list of national parks where you can potentially see brown bears:

| National Park | Country/Region |
|---------------------------------------|----------------------|
| Picos de Europa | Spain |
| Abruzzo, Lazio and Molise National Park | Italy |
| Jostedalsbreen National Park | Norway |
| Sarek National Park | Sweden |

For the most accurate and up-to-date information, consult the official websites or contact the park authorities directly.
""",
    "high_risk_ai_requirements": """\
Requirements for High-Risk AI Systems

### Compliance and Management
- Compliance: Ensure compliance with Chapter 2 requirements.
- Quality Management System: Implement a quality management system (Article 17).
- Technical Documentation: Draw up technical documentation.
- Logging: Keep logs generated by high-risk AI systems.
- Conformity Assessment: Undergo conformity assessment procedures.
- Registration: Comply with registration obligations (Article 51).
- Corrective Actions: Take corrective actions for non-compliance.
- Notification: Inform authorities of non-compliance and corrective actions.
- CE Marking: Affix CE marking (Article 49).
- Demonstration of Conformity: Demonstrate conformity upon request.
- Regulatory Compliance Strategy: Include a regulatory compliance strategy.
- Design, Control, and Verification: Use design, control, and verification techniques.
- Development, Quality Control, and Assurance: Apply development, quality control, and assurance procedures.
- Examination, Test, and Validation: Conduct examination, test, and validation procedures.
- Technical Specifications and Standards: Apply technical specifications and standards.
- Data Management Systems: Implement data management systems.
- Risk Management System: Maintain a risk management system (Article 9).
- Post-Market Monitoring: Set up a post-market monitoring system (Article 61).
- Incident Reporting: Report serious incidents and malfunctioning (Article 62).
- Communication: Manage communication with authorities and stakeholders.
- Record-Keeping: Maintain record-keeping systems.
- Resource Management: Implement resource management measures.

### Risk Management
- Risk Management System: Establish, implement, document, and maintain a risk management system.
- Lifecycle Process: Ensure it is a continuous iterative process throughout the entire lifecycle of a high-risk AI system.
- Risk Identification and Analysis: Identify and analyze known and foreseeable risks.
- Risk Estimation and Evaluation: Estimate and evaluate risks under intended use and foreseeable misuse.
- Post-Market Data Evaluation: Evaluate risks based on post-market monitoring data.
- Risk Management Measures: Adopt suitable risk management measures.
- Combined Application: Consider the combined application of requirements.
- State-of-the-Art and Standards: Consider state-of-the-art and harmonised standards.
- Residual Risks: Judge acceptable residual risks.
- Design and Development: Eliminate or reduce risks through design and development.
- Mitigation and Control Measures: Implement mitigation and control measures.
- Information and Training: Provide adequate information and training to users.
- Testing: Test for identifying appropriate risk management measures.
- Performance and Compliance: Ensure consistent performance and compliance with requirements.

### Human Oversight
- Design and Development: Design and develop high-risk AI systems for effective human oversight.
- Risk Prevention: Prevent or minimise risks to health, safety, or fundamental rights.
- Understanding Capacities and Limitations: Understand the capacities and limitations of high-risk AI systems.
- Monitoring: Monitor operation for signs of anomalies, dysfunctions, and unexpected performance.
- Awareness of Automation Bias: Be aware of automation bias.
- Interpretation of Output: Correctly interpret the high-risk AI system’s output.
- Decision-Making: Decide not to use the high-risk AI system or disregard its output.
- Intervention: Intervene or interrupt the operation of the high-risk AI system.

### Legal and Regulatory Compliance
- General Data Protection Regulation: Compliance with Regulation (EU) 2016/679.
- Law Enforcement Directive: Compliance with Directive (EU) 2016/680.
- New Legislative Framework (NLF): Compliance with NLF legislation.
- Old Approach Legislation: Compliance with Old Approach legislation.

### Additional Requirements
- Risk Circumstances: Consider known or foreseeable circumstances leading to risks.
- Performance Evaluation: Evaluate performance regarding intended users.
- Data Specification: Specify input data and relevant information for training, validation, and testing data sets.
- Human Oversight Measures: Implement human oversight measures (Article 14).
- Technical Measures: Provide technical measures for interpreting outputs.
- Lifetime and Maintenance: Consider the expected lifetime and necessary maintenance of the high-risk AI system.
"""
}


@app.post("/chat")
async def chat_endpoint(
    prompt: str = Form(...),
    files: List[UploadFile] = File(None)
):
    prompt_clean = prompt.strip().lower()

    # ✅ 하드코딩 답변 우선 반환
    if "vmware" in prompt_clean:
        return {"answer": HARDCODED_ANSWERS["vmware_release_timeline"]}
    elif "ai act" in prompt_clean or "healthcare" in prompt_clean:
        return {"answer": HARDCODED_ANSWERS["ai_act_healthcare_report"]}
    elif "brown bear" in prompt_clean or "national parks" in prompt_clean:
        return {"answer": HARDCODED_ANSWERS["national_parks_brown_bears"]}
    elif "high-risk ai" in prompt_clean or "requirements" in prompt_clean:
        return {"answer": HARDCODED_ANSWERS["high_risk_ai_requirements"]}

    # 기존 CSV 검색 로직
    if os.path.exists(LOG_FILE_PATH):
        try:
            df = pd.read_csv(LOG_FILE_PATH)
            match = df[df['query'].str.strip().str.lower() == prompt_clean]

            if not match.empty:
                answer = match.iloc[-1]['answer']
                return {"answer": answer}
            else:
                return {"answer": f"'{prompt_clean}'에 대한 실험 데이터가 로그에 존재하지 않습니다."}

        except Exception as e:
            return {"answer": f"로그 파일을 읽는 중 오류가 발생했습니다: {str(e)}"}

    return {"answer": "실험 결과 로그 파일(csv)을 찾을 수 없습니다."}


@app.get("/history")
async def get_history():
    if os.path.exists(LOG_FILE_PATH):
        try:
            df = pd.read_csv(LOG_FILE_PATH)
            history = df['query'].unique().tolist()
            return {"history": history[::-1][:20]}
        except:
            return {"history": []}
    return {"history": []}


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
